cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/<int:size_id>', views.cart_remove, name='cart_remove'),
]

modeshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('created/', views.order_created, name='order_created'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product, Size
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(product_id, request.POST)
    
    if form.is_valid():
        cd = form.cleaned_data
        quantity = cd['quantity']
        
        if cd['update']:
            cart.update_quantity(product_id, quantity)
        
        cart.add(
            product=product,
            size=cd['size'],
            quantity=quantity
        )
        
    return redirect('cart:cart_detail')


def cart_remove(request, product_id, size_id):
    cart = Cart(request)
    cart.remove(product_id, size_id)
    cart.save()
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    total_price = 0
    
    for item in cart:
        product_id = item['product_id']
        product = get_object_or_404(Product, id=product_id)
        selected_size = get_object_or_404(Size, id=item['size_id'])
        item['product'] = product
        item['size'] = selected_size

        item_total_price = item['quantity'] * item['product'].price
        total_price += item_total_price

        item['total_price'] = item_total_price
        item['form'] = CartAddProductForm(product_id, initial={'quantity': item['quantity'], 'size': selected_size})

    return render(request, 'cart/cart.html', {'cart': cart, 'total_price': total_price})

cart/templates/cart/cart.html
{% extends 'shop/base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static "/css/all.min.css" %}">
    <link rel="stylesheet" href="{% static "/css/cart.css"%}">
    <link rel="stylesheet" href="{% static "/css/media.css"%}">
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Products
    {% endif %}
{% endblock %}

{% block banner %}
{% endblock %}

{% block content %}
    {% if cart|length == 0 %}
        <p class="empty-cart">Корзина пуста</p>
    {% else %}
        <table class="cart_table">
            <thead class="cart_title">
                <th class="cart_product">
                    Товар
                </th>
                <th class="space_center"></th>
                <th class="cart_price">
                    Цена
                </th>
                <th class="cart_quantity">
                    Кол-во
                </th>
                <th class="cart_total">
                    Итого
                </th>
            </thead>
            <tbody class="cart_list">
                {% for item in cart %}
                    {% with product=item.product %}
                        {% with size=item.size %}
                            <tr class="cart_element">
                                <td class="cart_cover">
                                    <img src="{{ product.image.url }}" alt="">
                                </td>
                                <td class="cart_info">
                                    <p>
                                        <a href="{{ product.get_absolute_url }}" class="cart_link">{{ product.name }}</a>
                                        <br>
                                        Размер: {{ size.name }}
                                    </p>
                                </td>
                                <td class="cart_price">
                                    {{ item.product.price }}
                                </td>
                                <td class="cart_quantity">
                                    <form action="{% url 'cart:cart_add' item.product_id %}" method="post" id="cart-update-form">
                                        {% csrf_token %}
                                        {{ item.quantity }}
                                        {% comment %} <button type="submit" name="update" value="true">
                                            <i class="fa-light fa-arrows-rotate" style="color: #000000;"></i>
                                        </button> {% endcomment %}
                                    </form>
                                </td>
                                <td class="cart_total">
                                    {{ item.total_price }}
                                </td>
                                <td>
                                    <form action="{% url 'cart:cart_remove' item.product_id item.size_id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="total_cart_remove">
                                            <i class="fa-light fa-trash" style="color: #000000;"></i>
                                        </button>
                                    </form>                                    
                                </td>
                            </tr>
                        {% endwith %}
                    {% endwith %}
                {% endfor %}
            </tbody>
        </table>
    </form>
    <div class="total">
        <div class="content">
            <div class="total_title">
                ИТОГО
            </div>
            {% comment %} <div class="total_promo">
                <div class="total_promo_text">
                    Введите промокод
                </div>
                <div class="total_promo_form">
                    <input class="promo_form" type="text" placeholder="Введите промокод">
                    <button class="promo_button">Применить промокод</button>
                </div>
            </div>
            <div class="total_price">
                <div class="total_price_title">
                    Сумма
                </div>
                <div class="total_price_text">
                    {{ total_price }}
                </div>
            </div> {% endcomment %}
            <div class="total_sum">
                <div class="total_sum_title">
                    Всего к оплате
                </div>
                <div class="total_sum_text">
                    {{ total_price }}
                </div>
            </div>
            <form action="{% url 'orders:order_create' %}" method="get">
                <div class="total_button">
                    <button class="total_cart_button">Оформление Заказа</button>
                </div>
            </form>
        </div>
    </div>
    {% endif %}
    <form class="cart">
{% endblock %}