cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/<int:size_id>', views.cart_remove, name='cart_remove'),
]

modeshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
          name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', 
                       args=[self.slug])
    

class Product(models.Model):
    category = models.ForeignKey(Category, 
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    sizes = models.ManyToManyField('Size', related_name='products', blank=True)

    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])
        
class Size(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'sizes'

    def __str__(self):
        return self.name
    
class ProductSize(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_sizes')
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name_plural = 'product sizes'

    def __str__(self):
        return f'{self.product} - {self.size} ({self.quantity})'
    
    

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, ProductSize
from cart.forms import CartAddProductForm
# Create your views here.

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/index.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})
    
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm(product_id=id)
    product_sizes = ProductSize.objects.filter(product=product, quantity__gt=0)
    return render(request, 'shop/product/goods.html', {'product': product, 'cart_product_form': cart_product_form, 'product_sizes': product_sizes})

shop/templates/shop/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="/js/script.js"></script>
    {% block links %}{% endblock %}
    
    <title>{% block title%}MODE MOSCOW {% endblock %}</title>
</head>
<body>
    <div class="wrapper">
        <header>
            <div class="content">
                <div class="incontent">
                    <div class="social_block">
                        <div class="vk">
                            <a href="https://vk.com/mode_moscow"><i class="fa-brands fa-vk" style="color: #000000;"></i></a>
                        </div>
                        <div class="inst">
                            <a href="https://www.instagram.com/mode_moscow/"><i class="fa-brands fa-instagram" style="color: #000000;"></i></a>
                        </div>
                        <div class="tg">
                            <a href="https://t.me/mode_moscow"><i class="fa-brands fa-telegram" style="color: #000000;"></i>   </a>
                        </div>
                    </div>
                    <div class="logo">
                        <a href="{% url "shop:product_list" %}"><img src="{% static "/media/logo.svg" %}" alt=""></a>
                    </div>

                    <div class="cart">
                        <a href="{% url "cart:cart_detail" %}"><i class="fa-light fa-bag-shopping"></i></a>
                    </div>
                    <button  class="icon">
                        <hr>
                        <hr>
                        <hr>
                    </button>
                </div>
            </div>
        </header>
        <main>
            <div class="content">
                <div class="block_nav">
                    <div class="main_nav">
                        <ul>
                            <li {% if not category %}class="selected"{% endif %}>
                                <a href="{% url "shop:product_list" %}">All</a>
                            </li>
                            {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a> 
                                </li>
                            {% endfor %}                            
                        </ul>
                    </div>
                </div>
                <div class="incontent">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </main>
        <footer>
            <div class="content">
                <div class="incontent">
                    <div class="text_footer">
                        <a href="information.html">Information</a>
                        <a href="#">Privacy</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>